# レコメンデーション 

# 【問題1】アイテムベース
以下のような架空の旅行者のデータを使って簡単なアイテムベースのレコメンドを行う。 
下の表は、ハワイ、グアム、ロンドン、ニューヨークへ訪れた回数を記録した6人分の旅行者のデータである。
アイテム間の類似度行列を作る 
例えば、「ハワイ」と「ハワイとそのほかの国」とのコサイン類似度を計算してみると以下のように計算できる。 
これを各国分、計算して、類似度行列を出してみよう。

In [41]:
import numpy as np
data = np.array([
    [1,2,4,3],
    [1,1,2,4],
    [3,5,2,2],
    [3,4,2,3],
    [3,3,0,4],
    [3,3,1,4]])

target_user_data = np.array([[1,0,0,0]])

In [42]:
import numpy as np
def cosine_similarity_matrix (vectors):
    unit_vectors = vectors / np.linalg.norm(vectors, axis=1, keepdims=True)
    return np.matmul(unit_vectors, unit_vectors.T)

In [43]:
#アイテムごとのコサイン類似度行列
cos_matrix = cosine_similarity_matrix(data.T)

In [44]:
cos_matrix

array([[1.        , 0.97332853, 0.63259899, 0.89190174],
       [0.97332853, 1.        , 0.71956944, 0.83666003],
       [0.63259899, 0.71956944, 1.        , 0.75462449],
       [0.89190174, 0.83666003, 0.75462449, 1.        ]])

In [45]:
np.dot(target_user_data, cos_matrix)

array([[1.        , 0.97332853, 0.63259899, 0.89190174]])

## ハワイ以外だとグアムになりました。

### 【問題2】ユーザーベース
以下のようなデータがあった時に、user１に対して、レコメンドする方法を考えていきます。
ユーザーベースの手法は同じようなユーザを見つけてそのユーザと同じようなレコメンドをします。 
今回の方法は厳密なレコメンド手法とは異なりますが、実装を通して大まかなイメージを掴みましょう。

方法
ユーザーごとの相関行列を出す。 
ユーザーごとの相関行列を出してください。(今回はピアソンを使いましょう。)
アイテムベースの時は、アイテムに対して類似度行列を出しましたが、今回はユーザに対して使います。

評価の高い方を推薦する 
相関を出したら、最も相関の高い人のレコメンド結果を使ってuser1に対してレコメンドしてください。



In [107]:
#nanを-99で置いとく
u_data = np.array([
    [2,2,4, 3,3],
    [1,1,2,4,3],
    [0,5,2,2,5],
    [2,4,2,3,4],
    [1,3,0,4,1],
])

In [109]:
#欠損ちうめ
print((4 + 2 +3 + 4) / 4)
print((3 + 5 + 4  + 1) / 4)

3.25
3.25


In [110]:
C = np.corrcoef(u_data)

In [114]:
#相関行列　ユーザー１と相関が高いのはユーザ２
C

array([[ 1.        ,  0.50418417, -0.02756589, -0.29880715, -0.40006613],
       [ 0.50418417,  1.        ,  0.10613237,  0.19174125,  0.37340802],
       [-0.02756589,  0.10613237,  1.        ,  0.92253121,  0.19650211],
       [-0.29880715,  0.19174125,  0.92253121,  1.        ,  0.45643546],
       [-0.40006613,  0.37340802,  0.19650211,  0.45643546,  1.        ]])

## ユーザー１と相関が高いのはユーザ２なので 3, 4をレコメンドする
推薦システムのアルゴリズム(神嶌 敏弘)http://www.kamishima.net/archive/recsysdoc.pdf

推薦システム(神嶌 敏弘) (スライド)http://www.kamishima.net/archive/recsys.pdf